apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: 192.168.56.10:8082/voteapp/voting-app:latest
        env:
        - name: REDIS_HOST
          value: redis.vote-redis
        ports:
        - containerPort: 80
          name: vote
      imagePullSecrets:
      - name: nexus