apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vote-frontend
spec:
  rules:
  - host: vote-app-frontend.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 80