apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxOTIuMTY4LjU2LjEwOjgwODIiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiUWF6eHN3MTIzKiIsImVtYWlsIjoibmV4dXNAbmV4dXMuY29tIiwiYXV0aCI6IllXUnRhVzQ2VVdGNmVITjNNVEl6S2c9PSJ9fX0=
kind: Secret
metadata:
  name: nexus
type: kubernetes.io/dockerconfigjson