apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: worker
  name: worker
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template: 
    metadata: 
      labels: 
        app: worker
    spec: 
      containers: 
      - image: 192.168.56.10:8082/voteapp/voting-worker:latest
        name: worker
        env:
        - name: REDIS_HOST
          value: redis.vote-redis
        - name: POSTGRES_CONN_STRING
          value: "Server=db.vote-postgresql;Username=postgres;Password=postgres;"
      imagePullSecrets:
      - name: nexus